# Generated by Django 5.1.6 on 2025-03-24 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='products_orderitem',
        ),
    ]
