# Generated by Django 5.1.6 on 2025-03-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_user_password1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
    ]
