# Generated by Django 5.1.6 on 2025-03-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='raw_password',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
    ]
