# Generated by Django 5.1.7 on 2025-03-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_user_options_alter_user_managers_and_more'),
        ('products', '0018_order_customer_address'),
    ]

    operations = [
    ]
